project:
  name: HistoneLinker-Atlas
  version: 1.0

datasets:

  autism:
    expression_file: data/processed/autism/autism_vs_control_H1_stats.csv

  dlbc:
    alteration_file: data/processed/dlbc/dlbc_integrated_summary.csv
    normalized_file: data/processed/dlbc/dlbc_integrated_summary_normalized.csv

integration:
  output_file: data/processed/integration/ranked_histones.csv
